import type { NextPage } from "next";
import Head from "next/head";
import MainContainer from "../containers";
import styled from "styled-components";

const Home: NextPage = () => {
  return (
    <Wrapper>
      <Head>
        <title>WhatIf - A FOMO Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainContainer />
    </Wrapper>
  );
};

const Wrapper = styled.main`
  margin: 0 auto;
  width: 75%;
`;

export default Home;
